CREATE TABLE `adssort`.`USER` (
  `CIF` CHAR(36) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `PASSWORD` char(60) NOT NULL,
  `FIRSTNAME` nvarchar(50) NOT NULL,
  `LASTNAME` nvarchar(50) NOT NULL,
  `TIMEZONE_CODE` char(6) NOT NULL,
  `CREATED_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` VARCHAR(36) NOT NULL,
  `UPDATED_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(36) NOT NULL,
  `STATUS` TINYINT(1) NOT NULL
  PRIMARY KEY (`CIF`)
);


ALTER TABLE `adssort`.`USER`
ADD INDEX `INDEX_USER_EMAIL` (`EMAIL` ASC);


CREATE TABLE `adssort`.`MASTER_COUNTRY` (
`COUNTRY_CODE` CHAR(2) NOT NULL,
PRIMARY KEY (`COUNTRY_CODE`));

CREATE TABLE `adssort`.`MASTER_INDUSTRY` (
  `INDUSTRY_CODE` CHAR(3) NOT NULL,
  PRIMARY KEY (`INDUSTRY_CODE`));

CREATE TABLE `adssort`.`COMPANY` (
  `COMPANY_ID` CHAR(36) NOT NULL,
  `COMPANY_NAME` NVARCHAR(150) NOT NULL,
  `COMPANY_URL` NVARCHAR(255) NULL,
  `ADDRESS1` NVARCHAR(255) NOT NULL,
  `ADDRESS2` NVARCHAR(255) NULL,
  `CITY` NVARCHAR(45) NOT NULL,
  `STATE` NVARCHAR(45) NOT NULL,
  `POSTAL_CODE` NVARCHAR(11) NOT NULL,
  `COUNTRY_CODE` CHAR(2) NOT NULL,
  `INDUSTRY_CODE` CHAR(3) NOT NULL,
  PRIMARY KEY (`COMPANY_ID`));

  ALTER TABLE `adssort`.`COMPANY`
  ADD CONSTRAINT `FK_COUNTRY_CODE`
    FOREIGN KEY (`COUNTRY_CODE`)
    REFERENCES `adssort`.`MASTER_COUNTRY`(`COUNTRY_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

  ALTER TABLE `adssort`.`COMPANY`
    ADD CONSTRAINT `FK_INDUSTRY_CODE`
      FOREIGN KEY (`INDUSTRY_CODE`)
      REFERENCES `adssort`.`MASTER_INDUSTRY`(`INDUSTRY_CODE`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;

    CREATE TABLE `adssort`.`REL_USER_ROLE_COMPANY` (
      `CIF` CHAR(36) NOT NULL,
      `COMPANY_ID` CHAR(36) NOT NULL,
      `ROLE_ID` TINYINT(1) NULL,
      `ROLE_CUSTOM` VARCHAR(45) NULL,
      PRIMARY KEY (`CIF`, `COMPANY_ID`),
      INDEX `FK_COMPANY_ID_idx` (`COMPANY_ID` ASC),
      INDEX `INDEX_CIF_COMPANY_ID` (`COMPANY_ID` ASC, `CIF` ASC),
      CONSTRAINT `FK_CIF`
        FOREIGN KEY (`CIF`)
        REFERENCES `adssort`.`USER` (`CIF`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
      CONSTRAINT `FK_COMPANY_ID`
        FOREIGN KEY (`COMPANY_ID`)
        REFERENCES `adssort`.`COMPANY` (`COMPANY_ID`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION);

    CREATE TABLE `adssort`.`MASTER_TIMEZONE` (
      `TIMEZONE_VALUE` FLOAT(4,2) NOT NULL,
      `TIMEZONE_CODE` CHAR(6) NOT NULL,
      PRIMARY KEY (`TIMEZONE_CODE`));

      ALTER TABLE `adssort`.`USER`
      ADD CONSTRAINT `FK_TIMEZONE_CODE`
        FOREIGN KEY (`TIMEZONE_CODE`)
        REFERENCES `adssort`.`MASTER_TIMEZONE`(`TIMEZONE_CODE`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION;

        CREATE TABLE `adssort`.`RESET_PASSWORD_LIST` (
        `CIF` CHAR(36) NOT NULL,
        `RESET_KEY` CHAR(36) NOT NULL,
        `REQUEST_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (`CIF`),
        INDEX `IND_PASSWORDLIST_CIF` (`CIF` ASC),
        INDEX `IND_PASSWORDLIST_RESET_KEY` (`RESET_KEY` ASC),
        INDEX `IND_PASSWORDLIST_REQUEST_TIME` (`REQUEST_TIME` ASC),
        CONSTRAINT `FK_PASSWORDLIST_CIF`
          FOREIGN KEY (`CIF`)
          REFERENCES `adssort`.`USER` (`CIF`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION);

      CREATE TABLE `adssort`.`MASTER_DOMAIN_STATUS` (
      `DOMAIN_STATUS` CHAR(1) NOT NULL,
      `STATUS_DESCRIPTION` VARCHAR(200) NULL,
      PRIMARY KEY (`DOMAIN_STATUS`));

      CREATE TABLE `adssort`.`COMPANY_DOMAIN` (
        `COMPANY_ID` CHAR(36) NOT NULL,
        `DOMAIN_NAME` VARCHAR(253) NOT NULL,
        `DOMAIN_STATUS` CHAR(1) NOT NULL,
        PRIMARY KEY (`COMPANY_ID`, `DOMAIN_NAME`),
        INDEX `IND_COMP_DOMAIN_COM_IS` (`COMPANY_ID` ASC),
        CONSTRAINT `FK_COMP_DOMAIN`
          FOREIGN KEY (`COMPANY_ID`)
          REFERENCES `adssort`.`COMPANY` (`COMPANY_ID`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION,
        CONSTRAINT `FK_DOMAIN_STATUS`
          FOREIGN KEY (`DOMAIN_STATUS`)
          REFERENCES `adssort`.`MASTER_DOMAIN_STATUS` (`DOMAIN_STATUS`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION);

      CREATE TABLE `adssort`.`master_role` (
        `ROLE_ID` TINYINT(1) NOT NULL,
        `ROLE_DESCRIPTION` VARCHAR(50) NULL,
        PRIMARY KEY (`ROLE_ID`));

      CREATE TABLE `adssort`.`master_user_status` (
        `STATUS_ID` TINYINT(1) NOT NULL,
        `STATUS_DESCRIPTION` VARCHAR(45) NULL,
        PRIMARY KEY (`STATUS_ID`));

      CREATE TABLE `adssort`.`master_invitation_status` (
        `INVITE_STATUS` TINYINT(1) NOT NULL,
        `STATUS_DESCRIPTION` VARCHAR(45) NULL,
        PRIMARY KEY (`INVITE_STATUS`));

      CREATE TABLE `adssort`.`INVITATION_USER_COMPANY` (
        `EMAIL` VARCHAR(255) NOT NULL,
        `COMPANY_ID` CHAR(36) NOT NULL,
        `INVITE_KEY` CHAR(36) NOT NULL,
        `INVITE_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `ROLE_ID` TINYINT(1) NOT NULL,
        `ROLE_CUSTOM` VARCHAR(45) NULL,
        `INVITE_STATUS` TINYINT(1) NOT NULL,
        `INVITE_BY` CHAR(36) NOT NULL,
        `UPDATED_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `UPDATED_BY` VARCHAR(36) NOT NULL,
        PRIMARY KEY (`EMAIL`, `COMPANY_ID`));

      CREATE TABLE `adssort`.`role_map_authorization` (
        `ROLE_ID` TINYINT(1) NOT NULL,
        `AUTHORIZATION_LIST` VARCHAR(50) NOT NULL,
        PRIMARY KEY (`ROLE_ID`),
        CONSTRAINT `ROLE_ID`
          FOREIGN KEY (`ROLE_ID`)
          REFERENCES `adssort`.`master_role` (`ROLE_ID`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION);

      CREATE TABLE `adssort`.`MASTER_DOMAIN_RECORD_STATUS` (
        `RECORD_STATUS` TINYINT(1) NOT NULL,
        `STATUS_DESCRIPTION` VARCHAR(255) NULL,
        PRIMARY KEY (`RECORD_STATUS`));

      INSERT INTO adssort.MASTER_DOMAIN_RECORD_STATUS VALUES (1,'VALID');
      INSERT INTO adssort.MASTER_DOMAIN_RECORD_STATUS VALUES (2,'INVALID');

      CREATE TABLE `adssort`.`DOMAIN_DETAIL` (
        `DOMAIN_NAME` VARCHAR(253) NOT NULL,
        `RECORD_TYPE` VARCHAR(10) NOT NULL,
        `RECORD_STATUS` TINYINT(1) NOT NULL,
        `VALUE` VARCHAR(254) NOT NULL,
        `RECORD_NAME` VARCHAR(263) NOT NULL,
        PRIMARY KEY (`DOMAIN_NAME`, `RECORD_NAME`),
        INDEX `IND_DOMAIN_DETAIL` (`DOMAIN_NAME` ASC),
        CONSTRAINT `FK_RECORD_STATUS`
          FOREIGN KEY (`RECORD_STATUS`)
          REFERENCES `adssort`.`MASTER_DOMAIN_RECORD_STATUS` (`RECORD_STATUS`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION);
