INSERT INTO adssort.MASTER_INDUSTRY (INDUSTRY_CODE) VALUES ('MAR');
INSERT INTO adssort.MASTER_INDUSTRY (INDUSTRY_CODE) VALUES ('RET');
INSERT INTO adssort.MASTER_INDUSTRY (INDUSTRY_CODE) VALUES ('FAC');
INSERT INTO adssort.MASTER_INDUSTRY (INDUSTRY_CODE) VALUES ('ITS');
