INSERT INTO adssort.MASTER_ROLE (ROLE_ID,ROLE_DESCRIPTION) VALUES (1,'role.fullControl');
INSERT INTO adssort.MASTER_ROLE (ROLE_ID,ROLE_DESCRIPTION) VALUES (2,'role.marketing');
INSERT INTO adssort.MASTER_ROLE (ROLE_ID,ROLE_DESCRIPTION) VALUES (3,'role.manageUserOnly');
INSERT INTO adssort.MASTER_ROLE (ROLE_ID,ROLE_DESCRIPTION) VALUES (4,'role.reportOnly');
INSERT INTO adssort.MASTER_ROLE (ROLE_ID,ROLE_DESCRIPTION) VALUES (5,'role.custom');
INSERT INTO adssort.MASTER_ROLE (ROLE_ID,ROLE_DESCRIPTION) VALUES (6,'role.companyPredefined');
