INSERT INTO adssort.MASTER_DOMAIN_STATUS (DOMAIN_STATUS,STATUS_DESCRIPTION) VALUES ('A','Active');
INSERT INTO adssort.MASTER_DOMAIN_STATUS (DOMAIN_STATUS,STATUS_DESCRIPTION) VALUES ('I','In Active');
